app:
  name: "Groq RAG Chatbot"
  version: "1.0.0"
  environment: "development"

model:
  llm_provider: "groq"
  llm_name: "llama-3.1-8b-instant"
  embedding_model: "sentence-transformers/all-MiniLM-L6-v2"
  #embedding_model: "all-MiniLM-L6-v2"
  temperature: 0.7
  max_tokens: 512


rag:
  chunk_size: 800
  chunk_overlap: 100
  top_k: 4
  similarity_threshold: 0.75

retrieval:
  type: ["hybrid","dense","bm25"]       # "dense" | "bm25" | "hybrid"
  k_bm25: 30
  k_vector: 5
  weights: [0.3, 0.7]     # [w_bm25, w_vector] cho EnsembleRetriever
  k_final: 5              # sau rerank

reranker:
  enabled: true
  model_name: "cross-encoder/ms-marco-MiniLM-L-6-v2" 


